# -*- coding: utf-8 -*-
"""ML_Ass.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-nVOy2ss9DzkCrWj2RPDHfIZNHvUeLoN

Import Lib
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""open csv file"""

df = pd.read_csv('assignment1dataset.csv')
print (df.head())

"""Normalize function"""

def Normalize(arr):
  return ((arr-np.mean(arr))/np.std(arr))
 #return ((arr-np.min(arr))/(np.max(arr)-np.min(arr)))

"""Divide data"""

#Target
Y_Orginal=df['Energy Consumption'].values
Y=Normalize(Y_Orginal)
Y_mean=np.mean(Y_Orginal)
Y_std=np.std(Y_Orginal)
Y_max=np.max(Y_Orginal)
Y_min=np.min(Y_Orginal)
#Features for simple regression
X1=Normalize(df['Square Footage'].values)
X2=Normalize(df['Number of Occupants'].values)
X3=Normalize(df['Appliances Used'].values)
X4=Normalize(df['Average Temperature'].values)
#Features for multiple regression
X1234=Normalize(df.iloc[:, :4].values)
X12=Normalize(df.iloc[:, :2].values)
print(X12)

"""Basic Veriables"""

num_row=len(df)
feature_names = {
    'M1': 'Square Footage',
    'M2': 'Number of Occupants',
    'M3': 'Appliances Used',
    'M4': 'Average Temperature',
    'M5': 'Square Footage, Occupants, Appliances, Temperature',
    'M6': 'Square Footage, Occupants'
}

"""Simple Linear Regression function"""

def linear_regression(X,Y,learning_rate,epoch):
    m = 0
    c = 0
    for i in range(epoch):
      Y_hat=m*X+c
      c=c-learning_rate*(1/num_row)*np.sum(Y_hat-Y)
      m=m-learning_rate*(1/num_row)*np.sum((Y_hat-Y)*X)
    #predect
    Y_hat=m*X+c
    predect=Y_hat*Y_std+Y_mean
    #Evalu
    MSE=1/num_row*np.sum((Y_Orginal-predect)**2)
    return MSE

"""First group of hyber prameters"""

learning_rate1=[0.00001,0.0001,0.001,0.01,0.05,0.1]
epoch1=5000
MSE_For_all={}

"""Model 1   """

#learing rate = 0.01 is the best here
# but we can use 0.05,0.1,0.001
MSE=[]
for lr in learning_rate1:
   MSE1=linear_regression(X1,Y,lr,epoch1)
   MSE.append(MSE1)
   print (MSE1)
MSE_For_all['M1']= MSE

"""Model 2"""

#learing rate = 0.01 is the best here
# but we can use 0.05,0.1,0.001
MSE=[]
for lr in learning_rate1:
  MSE2=linear_regression(X2,Y,lr,epoch1)
  MSE.append(MSE2)
  print (MSE2)
MSE_For_all['M2']= MSE

"""Model 3"""

#learing rate = 0.01 is the best here
# but we can use 0.05,0.1,0.001
MSE=[]
for lr in learning_rate1:
  MSE3=linear_regression(X3,Y,lr,epoch1)
  MSE.append(MSE3)
  print (MSE3)
MSE_For_all['M3']= MSE

"""Model 4"""

#learing rate = 0.01 is the best here
# but we can use 0.05,0.1,0.001
MSE=[]
for lr in learning_rate1:
  MSE4=linear_regression(X4,Y,lr,epoch1)
  MSE.append(MSE4)
  print (MSE4)
MSE_For_all['M4']= MSE

"""Model 5"""

#learing rate = 0.01 is the best here
# but we can use 0.05,0.1
MSE=[]
for lr in learning_rate1:
  c=m1=m2=m3=m4=0
  for i in range(epoch1):
    Y_hat5=m1*X1+m2*X2+m3*X3+m4*X4+c
    c=c-lr*(1/num_row)*np.sum(Y_hat5-Y)
    m1=m1-lr*(1/num_row)*np.sum((Y_hat5-Y)*X1)
    m2=m2-lr*(1/num_row)*np.sum((Y_hat5-Y)*X2)
    m3=m3-lr*(1/num_row)*np.sum((Y_hat5-Y)*X3)
    m4=m4-lr*(1/num_row)*np.sum((Y_hat5-Y)*X4)
  #predect
  Y_hat5=m1*X1+m2*X2+m3*X3+m4*X4+c
  predect=Y_hat5*Y_std+Y_mean
  #Evalu
  MSE5=1/num_row*np.sum((Y_Orginal-predect)**2)
  MSE.append(MSE5)
  print (MSE5)
MSE_For_all['M5']= MSE

"""Model 6"""

#learing rate = 0.01 is the best here
# but we can use 0.05,0.1
MSE=[]
for lr in learning_rate1:
  c=m1=m2=m3=0
  for i in range(epoch1):
    Y_hat6=m1*X1+m2*X2+c
    c=c-lr*(1/num_row)*np.sum(Y_hat6-Y)
    m1=m1-lr*(1/num_row)*np.sum((Y_hat6-Y)*X1)
    m2=m2-lr*(1/num_row)*np.sum((Y_hat6-Y)*X2)
  #predect
  Y_hat6=m1*X1+m2*X2+c
  predect=Y_hat6*Y_std+Y_mean
  #Evalu
  MSE6=1/num_row*np.sum((Y_Orginal-predect)**2)
  MSE.append(MSE6)
  print (MSE6)
MSE_For_all['M6']= MSE

"""LR vs MSE"""

print(MSE_For_all.keys())
fig,axes=plt.subplots(2,3,figsize=(15,10))
fig.suptitle('Learning Rate vs MSE',fontsize=16)
axes=axes.flatten()
for i , (model,mse) in enumerate(MSE_For_all.items()):
  axes[i].plot(learning_rate1,mse,marker='o')
  axes[i].set_title(f"{model} ({feature_names.get(model, 'Unknown Features')})")
  axes[i].set_xlabel('Learning Rate')
  axes[i].set_ylabel('MSE')
  axes[i].set_xscale('log')
  axes[i].set_yscale('log')
  axes[i].grid(True)
plt.tight_layout()
plt.show()

"""Secend group of hyber prameters"""

learning_rate2=0.01
epoch2=[10,100,1000,10000,50000]
MSE_For_all2={}

"""Model 1"""

#epoch = 1000 is the best here (minimal mse)
MSE=[]
for e in epoch2:
   MSE1=linear_regression(X1,Y,learning_rate2,e)
   MSE.append(MSE1)
   print (MSE1)
MSE_For_all2['M1']= MSE

"""Model 2"""

#epoch = 1000 is the best here (minimal mse)
MSE=[]
for e in epoch2:
  MSE2=linear_regression(X2,Y,learning_rate2,e)
  MSE.append(MSE2)
  print (MSE2)
MSE_For_all2['M2']= MSE

"""Model 3"""

#epoch = 1000 is the best here (minimal mse)
MSE=[]
for e in epoch2:
  MSE3=linear_regression(X3,Y,learning_rate2,e)
  MSE.append(MSE3)
  print (MSE3)
MSE_For_all2['M3']= MSE

"""Model 4"""

#epoch = 1000 is the best here (minimal mse)
MSE=[]
for e in epoch2:
  MSE4=linear_regression(X4,Y,learning_rate2,e)
  MSE.append(MSE4)
  print (MSE4)
MSE_For_all2['M4']= MSE

"""Model 5"""

#epoch = 1000 is the best here (minimal mse)
MSE=[]
for e in epoch2:
  c=m1=m2=m3=m4=0
  for i in range(e):
    Y_hat5=m1*X1+m2*X2+m3*X3+m4*X4+c
    c=c-learning_rate2*(1/num_row)*np.sum(Y_hat5-Y)
    m1=m1-learning_rate2*(1/num_row)*np.sum((Y_hat5-Y)*X1)
    m2=m2-learning_rate2*(1/num_row)*np.sum((Y_hat5-Y)*X2)
    m3=m3-learning_rate2*(1/num_row)*np.sum((Y_hat5-Y)*X3)
    m4=m4-learning_rate2*(1/num_row)*np.sum((Y_hat5-Y)*X4)
  #predect
  Y_hat5=m1*X1+m2*X2+m3*X3+m4*X4+c
  predect=Y_hat5*Y_std+Y_mean
  #Evalu
  MSE5=1/num_row*np.sum((Y_Orginal-predect)**2)
  MSE.append(MSE5)
  print (MSE5)
MSE_For_all2['M5']= MSE

"""Model 6"""

#epoch = 1000 is the best here (minimal mse)
MSE=[]
for e in epoch2:
  c=m1=m2=0
  for i in range(e):
    Y_hat6=m1*X1+m2*X2+c
    c=c-learning_rate2*(1/num_row)*np.sum(Y_hat6-Y)
    m1=m1-learning_rate2*(1/num_row)*np.sum((Y_hat6-Y)*X1)
    m2=m2-learning_rate2*(1/num_row)*np.sum((Y_hat6-Y)*X2)
  #predect
  Y_hat6=m1*X1+m2*X2+c
  predect=Y_hat6*Y_std+Y_mean
  #Evalu
  MSE6=1/num_row*np.sum((Y_Orginal-predect)**2)
  MSE.append(MSE6)
  print (MSE6)
MSE_For_all2['M6']= MSE

"""Epoch vs MSE"""

print(MSE_For_all2.keys())
fig,axes=plt.subplots(2,3,figsize=(15,10))
fig.suptitle('Epoch vs MSE',fontsize=16)
axes=axes.flatten()
for i , (model,mse) in enumerate(MSE_For_all2.items()):
  axes[i].plot(epoch2,mse,marker='o')
  axes[i].set_title(f"{model} ({feature_names.get(model, 'Unknown Features')})")
  axes[i].set_xlabel('Epoch')
  axes[i].set_ylabel('MSE')
  axes[i].set_xscale('log')
  axes[i].set_yscale('log')
  axes[i].grid(True)
plt.tight_layout()
plt.show()

"""Conclosion"""

best_lr =0.01
best_epoch =1000
simple_mse_model={}
simple_mse_model['M1 ('+feature_names['M1']+')']=np.min(MSE_For_all2['M1'])
simple_mse_model['M2 ('+feature_names['M2']+')']=np.min(MSE_For_all2['M2'])
simple_mse_model['M3 ('+feature_names['M3']+')']=np.min(MSE_For_all2['M3'])
simple_mse_model['M4 ('+feature_names['M4']+')']=np.min(MSE_For_all2['M4'])
multi_mse_model={}
multi_mse_model['M5 ('+feature_names['M5']+')']=np.min(MSE_For_all2['M5'])
multi_mse_model['M6 ('+feature_names['M6']+')']=np.min(MSE_For_all2['M6'])

best_feature = min(simple_mse_model, key=(simple_mse_model.get))
best_mse = multi_mse_model['M5 ('+feature_names['M5']+')']


print (f"The best learning rate is {best_lr}")
print (f"The best epoch is {best_epoch}\n")

print ("MSE for models:")
for model,mse in simple_mse_model.items():
  print (f"{model}: {mse:.2f}")
for model,mse in multi_mse_model.items():
  print (f"{model}: {mse:.2f}")
print (f"\nThe best feature is \" {best_feature}\"")
print (f"The best MSE is\" {best_mse:.2f}\"")